### ISSUE TITLE
Irantalent website/service

### ISSUE THREAD

**Issue by voxxp** [rtbf-ir/rtbf.ir#126]
"name" : "ایران تلنت"
"website": "https://www.irantalent.com/"
"deleteurl": "ندارد"
"info": "سوالات متداول: برای لغو اشتراک، کارجو باید درخواست خود را از طریق ایمیل به آدرس info@irantalent.com ارسال کنند. نتیجه متعاقباً ارسال خواهد شد."

**Comment by Matin-B** [comment]
درود
لغو اشتراک با حذق حساب کاربری دو مبحث کاملا متفاوت هست و به همین دلیل پس از بررسی(ارتباط با پشتیبانی سایت) اضافه میشه.

سپاس بابت مشارکت.
