### ISSUE TITLE
اصلاح نیم فاصله‌ها در کل متن‌های سایت

### ISSUE THREAD

**Issue by amirshnll** [rtbf-ir/rtbf.ir#133]

**Comment by dashtaki** [comment]
سلام به نظرم این نیاز به توضیحات بیشتری دارد. حداقل برای من واضح  نیست. اگر ممکن هست با ذکر مثال یا سکرین شات موضوع رو بیشتر روشن کنید.

**Comment by amirshnll** [comment]
@dashtaki 

سلام مرسی از علاقتون به مشارکت در پروژه

این مورد توسط خودم در حال انجام هست برای همین جزییات خاصی ثبت نشده
موفق باشید
