### ISSUE TITLE
منوی اصلی در سایز موبایل درست نمایش داده نمیشود 

### ISSUE THREAD

**Issue by dashtaki** [rtbf-ir/rtbf.ir#136]
<img width="533" alt="Screenshot 2022-04-18 at 12 48 38" src="https://user-images.githubusercontent.com/12694761/163798313-5ccdb558-dbb3-4114-a143-b80d94892c7e.png">

**Comment by amirshnll** [comment]
@dashtaki 

لطفا جزییات بیشتری اعلام کنید.

**Comment by dashtaki** [comment]
با توجه به اینکه در پروژه از فریم ورک Bootstrap استفاده شده  و منو بر این اساس پیاده سازی شده , میتوان مشاهده کرد که در سایز موبایل تمام آیتم های منو باز است و دکمه بستن  مشاهده نمیشود. برای درک بیشتر میتوانید به [لینک اصلی مراجه بفرمایید](https://getbootstrap.com/docs/4.1/components/navbar/#supported-content) و صفحه را در سایز موبایل مشاهده کنید.
در حقیقت  در سایز موبایل باید به شکل زیر باشد:
<img width="417" alt="Screenshot 2022-04-20 at 09 10 07" src="https://user-images.githubusercontent.com/12694761/164171302-0e0ee811-842f-4de8-af9b-eca33e19448c.png">

**Comment by amirshnll** [comment]
oh hamburger menu :))))

منوی نسخه ی دسکتاپ یک منوی transparent می باشد با حفظ حالت دسکتاپ در صورت علاقه منوی همبرگری اضافه کنید

**Comment by amirshnll** [comment]
@dashtaki 

اگر علاقه دارید در رفع این مشکل مشارکت کنید
