### ISSUE TITLE
پیشنهاد 

### ISSUE THREAD

**Issue by Mehrankianiit** [rtbf-ir/rtbf.ir#144]
سلام. پیشنهاد می‌کنم قابلیت سرچ در دایرکتوری و فیلتر کردن و دسته بندی هم اضافه کنید تا راحت‌تر بشه سایت مورد نظر رو پیدا کرد.

**Comment by Matin-B** [comment]
درود
قابلیت  سرچ و چندین قابلیت دیگر در Service Roadmap (#112) لیست شده است اما متاسفانه مشارکت در پروژه بسیار کم هست. اگر علاقه‌مند باشید می‌تونید چنین قابلیتی را به سرویس اضافه کنید.

**Comment by amirshnll** [comment]
@Mehrankianiit 

مهران عزیز این قابلیت ها در بخش roadmap ذکر شده است من این issue رو میبندم اگر موردی بود روی issue مربوط به roadmap میتونیم در موردش صحبت کنیم
ارادت

**Comment by Mehrankianiit** [comment]
ممنونم. 
متاسفانه من توانایی کد نویسی رو ندارم اما خوشحال می‌شم بتونم به نحوی کمکی به پروژه کرده باشم.

**Comment by amirshnll** [comment]
@Mehrankianiit 


جستجو و فیلتر به سرویس اضافه شد
برای مشاهده روی لینک زیر بروید:
https://rtbf.ir/directory

#149 #148
