### ISSUE TITLE
yarketab - from email

### ISSUE THREAD

**Issue by amirshnll** [rtbf-ir/rtbf.ir#179]
servicename=yarketab
websiteurl=https://pishvayeasemani.yarketab.com/user/info/update?id=25174
deleteurl=
issuedescription=Ø­Ø°Ù Ú©Ø§Ø±Ø¨Ø±ÛŒ
submit=Ø«Ø¨Øª Ø³Ø§ÛŒØª/Ø³Ø±ÙˆÛŒØ³ Ø¬Ø¯ÛŒØ¯

**Comment by Matin-B** [comment]
ایمیل مربوطه به پشتیبانی سایت ارسال شد. پس از دریافت پاسخ از طرف پشتیبانی اطلاعات ثبت میشود.
