### ISSUE TITLE
هاست ایران

### ISSUE THREAD

**Issue by smmiri** [rtbf-ir/rtbf.ir#185]
من نسبت به ثبت سایت/سرویسم اعتراضم دارم برای نداشتن قابلیت حذف حساب کاربری دلیل مجموعه ی ما به شرح زیر می‌باشد:

....
هاست ایران قابلیت حذف اطلاعت ندارد. 
![image](https://github.com/rtbf-ir/rtbf.ir/assets/59976618/2f516085-01af-41b6-97a1-3b3b272442b9)

**Comment by Matin-B** [comment]
> من نسبت به ثبت سایت/سرویسم اعتراضم دارم برای نداشتن قابلیت حذف حساب کاربری دلیل مجموعه ی ما به شرح زیر می‌باشد:
> 
> .... هاست ایران قابلیت حذف اطلاعت ندارد. ![image](https://user-images.githubusercontent.com/59976618/241814969-2f516085-01af-41b6-97a1-3b3b272442b9.png)

درود
سپاس بابت اطلاع رسانی.
ایمیل مربوطه به تیم هاست ایران ارسال شد و پس از تایید وضعیت این سرویس تغییر خواهد کرد.
