### ISSUE TITLE
quera

### ISSUE THREAD

**Issue by creativealireza** [rtbf-ir/rtbf.ir#196]
"name" : "quera | کوئرا"
"website": "https://quera.org/"
"deleteurl": "ندارد"
"info": "وبسایت کوئرا امکان حذف حساب کاربری ندارد"

**Comment by amirshnll** [comment]
@creativealireza 
سلام با تشکر از مشارکتتون در سرویس حق فراموش شدن
سرویس کوئرا قبلا ثبت شده است اگر سرویس های دیگری مد نظر دارید در issue ها ثبت کنید.
ارادتمند
