### ISSUE TITLE
https://www.blogfa.com/

### ISSUE THREAD

**Issue by soleimani-saeed** [rtbf-ir/rtbf.ir#200]
"name" : "https://www.youtube.com/watch?v=1LGWG1CnaX4"
"website": "https://www.blogfa.com/"
"deleteurl": "https://www.blogfa.com/"
"info": "https://www.youtube.com/watch?v=1LGWG1CnaX4"

**Comment by amirshnll** [comment]
#stopspam

**Comment by soleimani-saeed** [comment]
![image](https://github.com/rtbf-ir/rtbf.ir/assets/67203240/a918faea-0441-4771-8e06-4ddfdbb2ef07)
اسپم چیه مرد مومن
نگاه کن عکس رو لطفا
