### ISSUE TITLE
مشکل پلاگین

### ISSUE THREAD

**Issue by soleimani-saeed** [rtbf-ir/rtbf.ir#202]
سایت خودتون رو هم بررسی نکردین هنوز!

![image](https://github.com/rtbf-ir/rtbf.ir/assets/67203240/6866127d-5b69-4669-8e9e-14dd46bae9a2)
![photo_۲۰۲۴-۰۱-۰۱_۱۱-۰۱-۱۸](https://github.com/rtbf-ir/rtbf.ir/assets/67203240/2d15cc86-aafb-4ae7-9c83-091be1172764)

**Comment by amirshnll** [comment]
@soleimani-saeed 

سلام سعید عزیز سایت سرویس حق فراموش شدن هیچ حساب کاربری‌ای ندارد و در حال حاضر هیچ داده‌ای به عنوان داده‌ی حساب کاربری در وبسایت نداریم.
موفق باشید

**Comment by soleimani-saeed** [comment]
![image](https://github.com/rtbf-ir/rtbf.ir/assets/67203240/4629beaf-57d5-45f9-8da4-ff905df7f7f9)
سپاس از پاسختون اما منظورم این بود که گمون میکنم افزونه با مشکل روبرو شده
و برای هیچ سایتی پیامی جز «باید بررسی بشه» نشون نمی‌ده
چه سایت کارزار-چه یوتیوب چه حتی بلاگفا که توی ویدئوتون خودتون به عنوان مثال ازش استفاده کرده بودید

**Comment by amirshnll** [comment]
@soleimani-saeed 

موضوع issue به ‍‍`مشکل پلاگین`تغییر پیدا کرد

**Comment by amirshnll** [comment]
من حالت های مختلف را تست کردم 

chrome

<img width="273" alt="Screenshot 2024-01-01 at 3 21 52 PM" src="https://github.com/rtbf-ir/rtbf.ir/assets/30009591/65076c91-4863-4537-98e6-13e54892896c">
<img width="264" alt="Screenshot 2024-01-01 at 3 21 57 PM" src="https://github.com/rtbf-ir/rtbf.ir/assets/30009591/2eab576c-7c27-4f3d-a7ed-fa1a43d9125f">
<img width="273" alt="Screenshot 2024-01-01 at 3 22 01 PM" src="https://github.com/rtbf-ir/rtbf.ir/assets/30009591/1bb9ad12-eb78-4f2a-b9c3-b17384b55c16">
<img width="276" alt="Screenshot 2024-01-01 at 3 22 10 PM" src="https://github.com/rtbf-ir/rtbf.ir/assets/30009591/050c4583-b777-4b79-b549-2786452fa4a2">
<img width="271" alt="Screenshot 2024-01-01 at 3 22 16 PM" src="https://github.com/rtbf-ir/rtbf.ir/assets/30009591/57236372-eb05-47ba-9472-66ba5f69ec2f">

**Comment by soleimani-saeed** [comment]
من امروز با افزونه‌تون آشنا شدم و ریختمش
پس برا من کاربر ویندوزی تازه نصب مشکل داره

**Comment by amirshnll** [comment]
> من امروز با افزونه‌تون آشنا شدم و ریختمش پس برا من کاربر ویندوزی تازه نصب مشکل داره

لطفا نسخه مرورگرتون رو بهم اطلاع بدین

**Comment by soleimani-saeed** [comment]
کروم
۱۲۰
از سافت ۹۸ گرفتم

**Comment by amirshnll** [comment]
من حالت های مختلف را تست کردم

firefox

<img width="315" alt="Screenshot 2024-01-01 at 3 26 40 PM" src="https://github.com/rtbf-ir/rtbf.ir/assets/30009591/7505dc3d-bc13-41e9-985b-96848829c728">
<img width="268" alt="Screenshot 2024-01-01 at 3 26 54 PM" src="https://github.com/rtbf-ir/rtbf.ir/assets/30009591/e681cd1f-f3e6-4f51-b781-a944a929311b">
<img width="270" alt="Screenshot 2024-01-01 at 3 26 59 PM" src="https://github.com/rtbf-ir/rtbf.ir/assets/30009591/7725e7a4-8465-4bd2-a9c5-a42ddbf90c5e">
<img width="274" alt="Screenshot 2024-01-01 at 3 27 02 PM" src="https://github.com/rtbf-ir/rtbf.ir/assets/30009591/9e63700f-c345-4ba1-9192-91ab924a24ad">
<img width="264" alt="Screenshot 2024-01-01 at 3 27 51 PM" src="https://github.com/rtbf-ir/rtbf.ir/assets/30009591/956abe30-dbd2-4b86-b683-173dd6771c62">

**Comment by amirshnll** [comment]
@soleimani-saeed 

لطفا سایت بلاگفا را به عنوان مثال باز کنید نتیجه رو اعلام کنید

**Comment by soleimani-saeed** [comment]
> کروم ۱۲۰ از سافت ۹۸ گرفتم

Google Chrome 120.

**Comment by soleimani-saeed** [comment]
> @soleimani-saeed
> 
> لطفا سایت بلاگفا را به عنوان مثال باز کنید نتیجه رو اعلام کنید

صبح باز کردم
گزارششم کردم
زیرش برام هشتگ اسپم نکن زدید😐

**Comment by amirshnll** [comment]
> > @soleimani-saeed
> > لطفا سایت بلاگفا را به عنوان مثال باز کنید نتیجه رو اعلام کنید
> 
> صبح باز کردم گزارششم کردم زیرش برام هشتگ اسپم نکن زدید😐

عذرخواهم issue بدون توضیح و جزییات بود با برچسب ثبت سرویس جدید به همین علت stopspam خورد این issue مجددا باز شد تا مشکل افزونه حل شود.
اگر جزییات بیشتری برای راهنمایی دارید اعلام کنید

**Comment by soleimani-saeed** [comment]
![image](https://github.com/rtbf-ir/rtbf.ir/assets/67203240/3240e2cd-9483-4529-8b90-93110a7fc8cf)

سپاس از مهر و ادبت
Google Chrome Version 120.0.6099.130 (Official Build) (64-bit)

**Comment by HoomanLashkarian** [comment]
![Uploading Screenshot (155).png…]()
واسه من داره کاملا درست کار میکنه مشکلی نمیبینم

**Comment by HoomanLashkarian** [comment]
![Screenshot (157)](https://github.com/rtbf-ir/rtbf.ir/assets/123248696/ba1765af-274c-40bf-b3e4-89c97b237955)
![Screenshot (155)](https://github.com/rtbf-ir/rtbf.ir/assets/123248696/bf022f92-495c-46ed-a7bf-e5aa2ef840fa)
واسه من داره کاملا درست کار میکنه مشکلی نمیبینم

**Comment by soleimani-saeed** [comment]
![image](https://github.com/rtbf-ir/rtbf.ir/assets/67203240/48bbf79b-5353-4797-b136-0bc5b6e8c355)
چه مسخره
اگه از سایت خودتون 
https://rtbf.ir/directory
وارد اون سایت بشم درست کار میکنه

ولی اگه مستقیم وارد یه سایت بشم و دکمه‌ی افزونه رو بزنم میگه باید بررسی بشه

**Comment by soleimani-saeed** [comment]
> کاملا درست

شمام از 
https://rtbf.ir/directory
وارد این سایتا شدید؟
+
ویندوز ۱۱ هستی

**Comment by amirshnll** [comment]
> ![image](https://private-user-images.githubusercontent.com/67203240/293584860-48bbf79b-5353-4797-b136-0bc5b6e8c355.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTE3NjQsIm5iZiI6MTcwNDExMTQ2NCwicGF0aCI6Ii82NzIwMzI0MC8yOTM1ODQ4NjAtNDhiYmY3OWItNTM1My00Nzk3LWIxMzYtMGJjNWI2ZThjMzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDEyMTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MGUxYzE4NzZiMDkxYTYyOTI1ZjhkZjUxY2RmMzdhZWRlMzhhNTNjNDA4Mzg5NDJhMDZlZDA2OTRmZDFjYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hNZmjcuTCxzERYpiTprGocNUx6lJytfuED0Haw6s0Qo) چه مسخره اگه از سایت خودتون https://rtbf.ir/directory وارد اون سایت بشم درست کار میکنه
> 
> ولی اگه مستقیم وارد یه سایت بشم و دکمه‌ی افزونه رو بزنم میگه باید بررسی بشه

بنده مشکل را مشاهده نکردم

**Comment by amirshnll** [comment]
@dashtaki @Matin-B 

 سلام لطفا این issue را بررسی کنید

**Comment by soleimani-saeed** [comment]
![image](https://github.com/rtbf-ir/rtbf.ir/assets/67203240/924f2bea-fdfb-4199-8612-e4b810a03187)
اگه مستقیم 
https://www.blogfa.com/
رو توو مرورگر 
Google Chrome Version 120.0.6099.130 (Official Build) (64-bit)
در ویندوز ۱۰
وارد کنم، افزونه کار نمی‌کنه
ولی اگه از سایت
https://rtbf.ir/directory
وارد همین بلاگفا بشم
افزونه بدرستی کار می‌کنه.

**Comment by amirshnll** [comment]
@soleimani-saeed 

سلام این مشکل را یافت کردم.
این مشکل دقیقا زمانی اتفاق می افتاد که سرویسی force redirect to https نداشت و شما نسخه ی این وبسایت با http را باز می کردید. این مشکل حل شده است و در مخزن های گیت هاب قابل دانلود است.

https://github.com/rtbf-ir/firefox-plugin

https://github.com/rtbf-ir/chrome-plugin


در بخش addons فایرفاکس هم بروزرسانی شده بعد از تایید فایرفاکس قابل آپدیت می باشد.
با تشکر از اطلاعتون
ارادتمند

**Comment by amirshnll** [comment]
@HoomanLashkarian سپاس از همراهیتون

**Comment by amirshnll** [comment]
@soleimani-saeed 

پلاگین فایرفاسک در mozilla addons تایید و قابل استفاده می باشد.
موفق باشید

https://addons.mozilla.org/addon/right-to-be-forgotten-iran/
