### ISSUE TITLE
new website/service

### ISSUE THREAD

**Issue by lostact** [rtbf-ir/rtbf.ir#203]
"name" : "استیم کلاب"
"website": "https://steamclub.ir"
"deleteurl": "https://steamclub.ir/my-account/wpf-delete-account/"
"info": "کاربران می توانند از طریق لینک موجود در پنل کاربری اکانت خود را حذف کنند"

**Comment by amirshnll** [comment]
@lostact 

سلام
با تشکر از مشارکت شما در سرویس حق فراموش شدن بعد از بررسی به سرویس اضافه می شود.
ارادتمند

**Comment by amirshnll** [comment]
@Matin-B

**Comment by Matin-B** [comment]
> "name" : "استیم کلاب" "website": "https://steamclub.ir" "deleteurl": "https://steamclub.ir/my-account/wpf-delete-account/" "info": "کاربران می توانند از طریق لینک موجود در پنل کاربری اکانت خود را حذف کنند"

درود
با تشکر از مشارکت شما.
سرویس مورد نظر به سایت اضافه شد.
