### ISSUE TITLE
new website/service خود گیت‌هاب

### ISSUE THREAD

**Issue by soleimani-saeed** [rtbf-ir/rtbf.ir#207]
"name" : "گیت هاب"
"website": "https://github.com/rtbf-ir/rtbf.ir/issues/new?assignees=amirshnll%2C+Matin-B&labels=new+website%2Fservice&template=new-service.md&title=new+website%2Fservice"
"deleteurl": "نمیدونم"
"info": "برای گیت‌هاب بررسی نشده هنوز؟ واقعا کسی به ذهنش خطور نکرده بود؟"
![image](https://github.com/rtbf-ir/rtbf.ir/assets/67203240/92ead968-4009-436d-9371-dc46f20701bd)

**Comment by amirshnll** [comment]
@soleimani-saeed 

سلام این سرویس با تمرکز بر سرویس های فارسی می باشد

**Comment by soleimani-saeed** [comment]
ایولا
دمتون گرم!
