### ISSUE TITLE
new website/service Google!

### ISSUE THREAD

**Issue by soleimani-saeed** [rtbf-ir/rtbf.ir#208]
"name" : "google.com"
"website": "google.com"
"deleteurl": "https://myaccount.google.com/?"
"info": "گوگل رو هم بررسی نکرده کسی تا حالا؟"
![image](https://github.com/rtbf-ir/rtbf.ir/assets/67203240/6cda2991-85e7-4078-bf46-977e21d84e9b)
آقا/خانم
من دارم اشتباه می‌زنم؟
ساز و کار این گزارش دادن به این شکل نیست؟
یا باگ داره و ی سری سایت بدیهی رو نشون نمی‌ده؟

**Comment by amirshnll** [comment]
@soleimani-saeed

سلام در حال حاضر این سرویس با تمرکز بر سرویس های فارسی می باشد

**Comment by soleimani-saeed** [comment]
دمتون گرم!
