### ISSUE TITLE
حذف

### ISSUE THREAD

**Issue by Semkoravy** [rtbf-ir/rtbf.ir#211]
من نسبت به ثبت سایت/سرویسم اعتراضم دارم برای نداشتن قابلیت حذف حساب‌کاربری دلیل مجموعه ی ما به شرح زیر می‌باشد:

....

**Comment by amirshnll** [comment]
@Semkoravy 

سلام لطفا جزییات بفرمایید

**Comment by Matin-B** [comment]
> من نسبت به ثبت سایت/سرویسم اعتراضم دارم برای نداشتن قابلیت حذف حساب‌کاربری دلیل مجموعه ی ما به شرح زیر می‌باشد:
> 
> ....

درود
لطفا به جهت اصلاح اطلاعات اطلاعات تکمیلی در خصوص سرویس مربوطه ارسال کنید.
