### ISSUE TITLE
فیدبک: وبسایت طرفداری

### ISSUE THREAD

**Issue by amirshnll** [rtbf-ir/rtbf.ir#218]
من نسبت به ثبت سایت/سرویسم اعتراضم دارم برای نداشتن قابلیت حذف حساب‌کاربری دلیل مجموعه ی ما به شرح زیر می‌باشد:

....

@Matin-B 

https://twitter.com/portaltintin/status/1743038911667175666

بررسی شود.

**Comment by Matin-B** [comment]
توییت در دسترس نیست و قبلا این مورد از طریق پشتیبانی رسمی وبسایت طرفداری بررسی شده است.
