### ISSUE TITLE
اسنپ فود

### ISSUE THREAD

**Issue by MortezaHeydari97** [rtbf-ir/rtbf.ir#229]
من نسبت به ثبت سایت/سرویسم اعتراضم دارم برای نداشتن قابلیت حذف حساب‌کاربری دلیل مجموعه ی ما به شرح زیر می‌باشد:

هک شدیم رفت، حداقل امکان حذف بزارید الان بتونم یه غلطی بکنیم یه حرکتی بزنیم.
توی هک بعدی دیتامون نباشه حداقل

**Comment by amirshnll** [comment]
@MortezaHeydari97 

سلام مرتضی عزیز
با تشکر از مشارکت شما در سرویس حق فراموش شدن سرویس اسنپ فود از قبل در دایرکتوری موجود می باشد. طبق اطلاعیه‌ی اسنپ فود به زودی این قابلیت اضافه می‌شود.
