### ISSUE TITLE
ابرآروان

### ISSUE THREAD

**Issue by hatamiarash7** [rtbf-ir/rtbf.ir#231]
با سلام. شرکت ابرآروان اجازه حذف حساب کاربری را تحت شرایط خاص به کاربر خواهد داد. متن رسمی :

> کاربر با رعایت شرایطی که در ادامه گفته خواهد شد، می‌تواند حساب کاربری خود را حذف یا غیرفعال کند:
> برای این کار لازم است کاربر درخواست مکتوب خود را به آدرس ایمیل support@arvancloud.ir ارسال کند. ابر آروان پس از بررسی این درخواست، امکان حذف یا غیرفعال کردن حساب را به کاربر اعلام خواهد کرد.
> به دلایل قانونی (مبارزه با پولشویی و کلاهبرداری‌های اینترنتی) حتا پس از تایید امکان حذف حساب کاربری، اطلاعات و تراکنش‌های مالی آن حساب، نزد ابر آروان باقی خواهد ماند.

لینک اصلی: [شرایط استفاده از خدمات ابرآروان](https://www.arvancloud.ir/fa/legal/terms)

**Comment by amirshnll** [comment]
<img width="1190" alt="Screenshot 2024-01-13 at 8 38 27 AM" src="https://github.com/rtbf-ir/rtbf.ir/assets/30009591/ebd8ad4b-46de-40f1-b113-058f8d462e4d">

لینک مورد تایید می باشد

**Comment by amirshnll** [comment]
@hatamiarash7 

سلام با تشکر از مشارکتتان. اطلاعات مورد نظر این سرویس اصلاح شد.
موفق باشید
