### ISSUE TITLE
Clarify - karzar

### ISSUE THREAD

**Issue by alisadeqinia** [rtbf-ir/rtbf.ir#244]
"name" : "کارزار"
"website": "https://www.karzar.net/"
"deleteurl": "https://www.karzar.net/panel/tickets"
"info": ""

**Comment by amirshnll** [comment]
@alisadeqinia 

 وبسایت کارزار از قبل در سرویس وجود دارد من این issue را تغییر نوع می دهم که مجددا وضعیت فعلی بررسی شود.

**Comment by amirshnll** [comment]
@Matin-B بررسی شود

**Comment by Matin-B** [comment]
> "name" : "کارزار" "website": "https://www.karzar.net/" "deleteurl": "https://www.karzar.net/panel/tickets" "info": ""

درود
تشکر بابت مشارکت و اطلاع رسانی.
وضعیت وبسایت کارزار بر اساس صفحه [سیاست‌نامه حریم خصوصی](https://www.karzar.net/privacy-policy) رسمی بروزرسانی شد.
