### ISSUE TITLE
new website/service

### ISSUE THREAD

**Issue by iyashar** [rtbf-ir/rtbf.ir#251]
"name" : "Digikala"
"website": "https://www.digikala.com/"
"deleteurl": ""
"info": ""

**Comment by amirshnll** [comment]
@iyashar 
سلام مرسی از اینکه علاقه به مشارکت در سرویس حق فراموش شدن داشتید.
سرویس مورد نظر شما قبلا در دایرکتوری ثبت شده است اگر اطلاعات جدید دارید می توانید برای ما ارسال کنید.
وضعیت سرویس مورد نظر در دایرکتوری با برچسب حذف حساب کاربری سخت علامت گذاری شده است و توضیحات آن به شرح زیر است:

> از طریق فرم صفحه تماس با ما تصویر کارت ملی مالک پروفایل (احراز‌هویت) به همراه متن: اینجانب ..... به دلیل ..... درخواست حذف اکانت کاربری با شماره همراه..... و نمونه کد سفارش ..... را دارم. ارسال کنید.
