### ISSUE TITLE
روبیکا : تغییر مدت زمان لازم برای حذف حساب

### ISSUE THREAD

**Issue by AmirAref** [rtbf-ir/rtbf.ir#256]
سلام ، مدت زمان گذشته ( از ورود به حساب ) لازم برای حذف حساب در روبیکا به **10** روز تغییر پیدا کرده است.

<img width="350" src="https://github.com/rtbf-ir/rtbf.ir/assets/81515807/d2728b77-4fae-42d8-9e11-d4fbfd482fb9">

**Comment by amirshnll** [comment]
@AmirAref 

سلام سپاس از مشارکت شما در سرویس حق فراموش شدن این موضوع پس از بررسی در سرویس اعمال می شود.

**Comment by amirshnll** [comment]
@Matin-B 
سلام لطفا بررسی شود

**Comment by amirshnll** [comment]
اصلاح شد
