### ISSUE TITLE
https://aqayepardakht.ir/

### ISSUE THREAD

**Issue by Saliizan** [rtbf-ir/rtbf.ir#262]
"name" : "آقای پرداخت"
"website": "https://aqayepardakht.ir"
"deleteurl": "non"
"info": "ارائه دهنده درگاه پرداخت واسط"

**Comment by amirshnll** [comment]
@Saliizan سلام سپاس از اینکه در سرویس حق فراموش شدن مشارکت می‌کنید سرویس مورد نظر در حال حاضر در دایرکتوری سرویس‌ها موجود نیست و پس از بررسی به دایرکتوری اضافه می‌شود.

**Comment by amirshnll** [comment]
@Matin-B لطفا بررسی شود
