### ISSUE TITLE
حق فراموش شدن سایت پونیشا

### ISSUE THREAD

**Issue by BahramElf** [rtbf-ir/rtbf.ir#264]
در سایت حق فراموش شدن برای پونیشا اینطور آمده:
"برای مسدود سازی حساب‌کاربری از [بخش پشتیبانی](https://rtbf.ir/ponisha.ir/support/new-ticket) اقدام کنید. همچنین جهت کسب اطلاعات بیشتر به صفحه "[چطور حساب‌کاربری را حذف کنم؟](https://rtbf.ir/ponisha.ir/help/article/%DA%86%D8%B7%D9%88%D8%B1-%D8%AD%D8%B3%D8%A7%D8%A8-%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1%DB%8C-%D8%B1%D8%A7-%D8%AD%D8%B0%D9%81-%DA%A9%D9%86%D9%85%D8%9F/)" مراجعه کنید."
در صورتی که این صفحه وجود ندارد و 404 هست و پشتیبانی این وب سایت هم اعلام میکنه که هیچ گونه امکان حذف یا حتی تغییر اطلاعات حساب کاربری مثل ایمیل یا تلفن و نام و... وجود نداره.

**Comment by amirshnll** [comment]
سلام بهرام عزیز موردی که گفتی ۴۰۴ میشه مشکل از سمت لینک‌های وبسایت بود. (اصلاح شد)
در ارتباط با روش حذف حساب کاربری در پونیشا این صفحه رو مطالعه کنید:
https://ponisha.ir/help/article/چطور-حساب-کاربری-را-حذف-کنم؟/

اگر نکته‌ای بود که متفاوت با اطلاعات ما بود از همین طریق هب ما اطلاع بده تا بتوانیم اطلاعاتمان را اصلاح کنیم
