### ISSUE TITLE
ایران سرور

### ISSUE THREAD

**Issue by MortezaHeydari97** [rtbf-ir/rtbf.ir#269]
من نسبت به ثبت سایت/سرویسم اعتراضم دارم برای نداشتن قابلیت حذف حساب‌کاربری دلیل مجموعه ی ما به شرح زیر می‌باشد:
ایران سرور هیچ خدمات به درد بخوری ارائه نمیده. نه uptime درست و حسابی و نه هیچی و نه سرویس خاصی برای framework های روز دنیا.
امیدوارم بتونم قبل از هک شدنش دیتامو از توش حذف کنم.

با تشکر از تیم خوب rtbf.ir

**Comment by amirshnll** [comment]
@MortezaHeydari97 
سلام مرتضی جان سرویس حق فراموش شدن سرویسی برای بررسی علت حذف حساب کاربری و عدم کیفیت سرویس ها نیست از این جهت این موارد رو نیاز نیست به عنوان issue ثبت کنید.
در حال حاضر ایران سرور از طریق ثبت تیکت امکان حذف حساب کاربری را برای شما ارائه می‌دهد.
موفق باشید
